[2023-11-26 11:18:49,875] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:18:49] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:18:50,217] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:18:50] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:19:18,481] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:19:18] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:20:46,394] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:20:46] "GET /cliente?cpf=10010010050 HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:22:08,377] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:22:08] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:24:23,184] WARNING get_cliente() L104  Erro ao buscar cliente '10010010051.0', Cliente não encontrado na base :/ - call_trace=C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py L104 
[2023-11-26 11:24:23,188] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:24:23] "[33mGET /cliente?cpf=10010010051 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:24:30,744] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:24:30] "GET /cliente?cpf=10010010225 HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:25:10,090] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:25:10] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:25:38,927] WARNING add_cliente() L54   Erro ao adicionar cliente '10010010225.0', Cliente de mesmo cpf já salvo na base :/ - call_trace=C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py L54  
[2023-11-26 11:25:38,929] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:25:38] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:29:02,533] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:29:02] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:29:17,558] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:29:17] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:29:37,924] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:29:37] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:29:41,982] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:29:41] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:29:51,600] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:29:51] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:29:57,267] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:29:57] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:30:10,231] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:30:10] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:30:38,288] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:30:38] "[33mPOST /produto HTTP/1.1[0m" 404 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:31:22,103] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:31:22] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:31:34,015] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:31:34] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:31:36,709] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:31:36] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 11:35:26,544] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 11:35:26] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:00:10,841] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:00:10] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:00:35,321] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:00:35] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:00:38,355] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:00:38] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:00:40,693] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:00:40] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:04:55,438] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:04:55] "[33mPOST /produto HTTP/1.1[0m" 404 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:05:00,143] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:05:00] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:05:02,706] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:05:02] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:07:39,087] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:07:39] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:08:03,036] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    cliente_cpf = unquote(unquote(query.cpf))
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 12:08:03,084] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:08:03] "[35m[1mDELETE /cliente?cpf=10010010225 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
