[2023-11-26 16:01:55,652] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    cliente_cpf = unquote(unquote(query.cpf))
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 16:01:55,899] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:01:55] "[35m[1mDELETE /cliente?cpf=20020020020 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:02:28,579] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:02:28] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:04:51,158] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:04:51] "OPTIONS /cliente?cpf=10010010225 HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:04:51,273] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    cliente_cpf = unquote(unquote(query.cpf))
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 16:04:51,304] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:04:51] "[35m[1mDELETE /cliente?cpf=10010010225 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:05:21,638] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:05:21] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:07:27,633] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:07:27] "GET /cliente?cpf=10010010225 HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:12:51,911] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:12:51] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:12:54,386] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:12:54] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:12:59,431] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:12:59] "OPTIONS /cliente?cpf=20020020020 HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:12:59,442] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    cliente_cpf = query.cpf
                          ^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 16:12:59,527] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:12:59] "[35m[1mDELETE /cliente?cpf=20020020020 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:13:03,688] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:13:03] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:17:00,811] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:17:00] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
